# Imagen base
FROM node:22.16.0-alpine

# Directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY . .

# Exponer el puerto
EXPOSE 4001

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]